default_language_version:
    python: python3.7
repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.4.0
  hooks:
    - id: nbqa-pyupgrade
      args: [--py37-plus]
    - id: nbqa-isort
    - id: nbqa-black
    - id: nbqa-flake8
      args: ['--config=settings.ini']
- repo: local
  hooks:
    - id: nbdev-clean
      name: nbdev-clean
      description: To avoid pointless conflicts while working with jupyter notebooks (with different execution counts or cell metadata).
      additional_dependencies: [nbdev>=2.1.1]
      entry: nbdev_clean
      language: python
      pass_filenames: false
    - id: nbdev-docs
      name: nbdev-docs
      description: Generate docs
      additional_dependencies: [nbdev>=2.1.1]
      entry: nbdev_docs
      language: python
      pass_filenames: false
ci:
    skip: [nbdev-docs]
